import { Check, Lightbulb, Sparkles, Volume2 } from "lucide-react";
import type { Feature } from "./interfaces";

export const MALAGASY_RULES = {
  invalidCombos: ["nb", "mk", "dt", "bp", "sz"],
  invalidStarts: ["nk"],
  prefixes: [
    "maha",
    "mpan",
    "mpam",
    "man",
    "mam",
    "mi",
    "ma",
    "fan",
    "fam",
    "fi",
    "an",
    "am",
  ],
  suffixes: ["ana", "ina", "na"],
};

export const MALAGASY_VOCAB = new Set([
  "misaotra",
  "salama",
  "veloma",
  "tsy",
  "eny",
  "trano",
  "fianarana",
  "asa",
  "vary",
  "rano",
  "sakafo",
  "manao",
  "mandeha",
  "mipetraka",
  "mihinana",
  "mitomany",
  "mihira",
  "manoratra",
  "mamaky",
  "manosika",
  "mahita",
  "razana",
  "famadihana",
  "fianakaviana",
  "ray",
  "reny",
  "zanaka",
  "antananarivo",
  "antsirabe",
  "toamasina",
  "mahajanga",
  "toliara",
  "madagascar",
  "malagasy",
  "tanindrazana",
  "fitiavana",
  "fahalalana",
  "izay",
  "ity",
  "io",
  "ireo",
  "ny",
  "sy",
  "na",
  "fa",
  "raha",
  "nefa",
  "dia",
  "ary",
  "koa",
  "foana",
  "indrindra",
  "be",
  "kely",
  "lehibe",
  "tsara",
  "ratsy",
  "faly",
  "malahelo",
  "hendry",
  "adala",
  "mahery",
  "malemy",
  "fotsy",
  "mainty",
  "mena",
  "maitso",
  "manga",
]);

export const FEATURES: Feature[] = [
  {
    id: "spell",
    icon: Check,
    label: "Correcteur",
    color: "bg-blue-500",
    active: true,
  },
  {
    id: "lemma",
    icon: Sparkles,
    label: "Lemmatisation",
    color: "bg-purple-500",
    active: false,
  },
  {
    id: "translate",
    icon: Lightbulb,
    label: "Traduction",
    color: "bg-green-500",
    active: false,
  },
  {
    id: "tts",
    icon: Volume2,
    label: "Synthèse Vocale",
    color: "bg-orange-500",
    active: true,
  },
];

export const EDITOR_CONFIG = {
  placeholder: "Soraty eto ny textinao... (Écrivez votre texte ici...)",
  height: "600px",
  spellCheckDelay: 300,
};
